language: scala
scala:
  - 2.11.8
  - 2.11.11
  - 2.12.0
  - 2.12.1
  - 2.12.2
  - 2.12.3
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt clean coverage test
after_success:
  - sbt coverageReport coveralls
